### ISSUE TITLE
error TS2304: Cannot find name 'Blob'

### ISSUE THREAD

**Issue by jojomatik** [socketio/engine.io-parser#128] opened 2022-04-29 18:44 UTC
**Describe the bug**
An error is thrown while running `tsc` in my typescript project using `engine.io-parser` on version `v5.0.3`.

```
Run cd backend && tsc
  cd backend && tsc
  shell: /usr/bin/bash -e {0}
Error: ../node_modules/engine.io-parser/build/esm/commons.d.ts(7,81): error TS2304: Cannot find name 'Blob'.
Error: Process completed with exit code 2.
```

**To Reproduce**

Please fill the following code example:

*not applicable*

engine.io-parser version: `v5.0.3`

**Expected behavior**
`tsc` runs without any issues as it does on version `v5.0.0`

**Platform:**
 - Software: tsc
 - OS: ubuntu

**Additional context**
The logs of the workflows can be found here https://github.com/jojomatik/blockcluster/runs/6233313889 (`v5.0.0`) and here https://github.com/jojomatik/blockcluster/runs/6233323368 (`v5.0.3`). The respective commits are linked from within the workflows.

It might be possible that the problem has to be solved somewhere else in the socket.io dependency chain but the error message lead me here. Here is the link to the commit that fails https://github.com/jojomatik/blockcluster/commit/5cecdce19266e094efab2f586f4f40fe646a942f. It shows all upgraded dependencies of that might cause the issue.

**Comment by darrachequesne** [comment] 2022-04-30 08:40
That's weird, `Blob` is used [there](https://github.com/socketio/engine.io-parser/blob/4952193c0444f554489650725ae90ca4586298c5/lib/commons.ts#L29) and should be found [there](https://github.com/microsoft/TypeScript/blob/99ffa394a838a5528d6118fb3c23f81fd8e99ab2/lib/lib.dom.d.ts#L2418-L2425):

```ts
interface Blob {
    readonly size: number;
    readonly type: string;
    arrayBuffer(): Promise<ArrayBuffer>;
    slice(start?: number, end?: number, contentType?: string): Blob;
    stream(): ReadableStream;
    text(): Promise<string>;
}
```

Also, I am not able to reproduce with the `tsconfig.json` in your project: https://github.com/socketio/socket.io-fiddle/tree/engine.io-parser/issues/128

**Comment by darrachequesne** [comment] 2022-04-30 12:16
This should be fixed by https://github.com/socketio/engine.io-parser/commit/039b45cc65b50acc1f9da42ad605eaccb8ccbcde, included in `engine.io-parser@5.0.4`.

**Closed by darrachequesne** 2022-04-30 12:16 UTC

**Comment by jojomatik** [comment] 2022-04-30 12:56
Thanks for the quick action, the CI on https://github.com/jojomatik/blockcluster/pull/402 now completes successfully.
